export type DishType = {
  mainCategory: any;
  parcelOptions: any;
  averageRating: number;
  reviews: any[];
  availableBefore: any;
  isActive: any;
  isPopular: any;
  calories: string;
  isNewDish: any;
  servings: number;
  _id: string | null | undefined;
  name: string;
  kcal: string;
  image: string;
  price: string;
  weight: string;
  isNew?: boolean;
  isHot?: boolean;
  menu: string[];
  quantity?: number;
  description: string;
  isRecommended?: boolean;
  dietaryPreferences?: string[];
};
